# Generated by Django 2.1.15 on 2020-06-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='player_id',
            field=models.ManyToManyField(related_name='game_id', through='game.PlayerGameInfo', to='game.Player'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='attempts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='is_user_creator',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
            preserve_default=False,
        ),
    ]
