# Generated by Django 2.1.15 on 2020-06-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200629_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_number',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='min_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(),
        ),
    ]
