# Generated by Django 2.1.15 on 2020-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200629_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_number',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=9),
        ),
    ]
