# Generated by Django 2.1.15 on 2020-06-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200629_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=7),
        ),
    ]
