# Generated by Django 2.1.15 on 2020-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200629_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='attempts_count',
        ),
        migrations.AddField(
            model_name='game',
            name='attempts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=2),
        ),
    ]
